#!/bin/bash

####
#### Patrick Dell precision m4700 F19
####

# old blitz
#with_blitz=/usr/local/blitz1
# new blitz
with_blitz=/usr/local/blitz2

with_hdf4=/usr/include/hdf,/usr/lib64/hdf
enable_hdf5_output=yes
with_hdf5=/usr/include,/usr/lib64

with_fftw3=yes

enable_mpi=no

enable_cxx_flags_preset=no

CXX=icpc

#CXXFLAGS="-xSSE4.2 -O3 -restrict -vec-report1 -no-prec-div -ansi-alias"
#CXXFLAGS="-xSSE4.2 -O3 -ipo -restrict -vec-report1 -no-prec-div -no-ansi-alias"
# D__GNUC_MINOR__=5 is a trick to disable float128 support for fftw3 which
# creates trouble
#CXXFLAGS="-D__GNUC_MINOR__=5 -xSSE4.2 -O3 -ip -restrict -vec-report1 -no-prec-div -no-ansi-alias"
CXXFLAGS="-xSSE4.2 -O3 -ip -restrict -qopt-report=1 -no-prec-div -no-ansi-alias"
