#!/bin/bash 

# CINECA IBM SP6 sp.sp6.cineca.it

export PATH=$PATH:/cineca/prod/tools/tcl/8.5.7/xl--10.1/bin/
. /cineca/prod/environment/module/3.1.6/none/init/bash 

module load autoload fftw
module load autoload hdf4

with_blitz=$HOME
with_fftw3=$FFTW_INC,$FFTW_LIB
with_hdf4=$HDF4_HOME 
enable_cxx_flags_preset=no
enable_optimize=no 
enable_64bit=yes 

CC=xlc 
CXX=xlC 
CXXFLAGS="-O0 -g -C"

LDFLAGS="-L$SZLIB_LIB -L$ZLIB_LIB"

enable_mpi=yes

MPICXX=mpCC 

