#!/bin/bash 

# CINECA IBM SP6 sp.sp6.cineca.it

export PATH=$PATH:/cineca/prod/tools/tcl/8.5.7/xl--10.1/bin/
. /cineca/prod/environment/module/3.1.6/none/init/bash

module load autoload fftw
module load autoload hdf4
module load autoload profile/advanced scalasca

with_blitz=$HOME
with_fftw3=$FFTW_INC,$FFTW_LIB
with_hdf4=$HDF4_HOME 
enable_cxx_flags_preset=no
enable_optimize=no 
enable_64bit=yes 

CC=xlc 
CXX=xlC 
# mpi-scalasca-O0 and mpi-new-scalasca-O0
#CXXFLAGS="-O0 -g -C"
# mpi-scalasca-O3
#CXXFLAGS="-O3 -qstrict -qstrict_induction -qinline -qansialias -qhot -qunroll=yes -qarch=pwr6 -qtune=pwr6 -qipa" 
# mpi-new-scalasca-O3
CXXFLAGS="-O3 -qstrict -qstrict_induction -qansialias -qhot -qunroll=yes -qarch=pwr6 -qtune=pwr6" 

LDFLAGS="-L$SZLIB_LIB -L$ZLIB_LIB"

enable_mpi=yes

MPICXX="skin mpCC" 

